### PR TITLE
Added gui support

### PR DESCRIPTION
**Pull request by bolopenguin**
I have implemented a simple GUI following the work of torch-ngp.

How to use it:
`python show_gui.py --root_dir /path/to/data/Lego --ckpt_path /path/to/checkpoint/epoch=14.ckpt`

Example of usage:

https://user-images.githubusercontent.com/48405697/181521050-90e4f2a9-89d6-4aaa-b258-862b2b9fcc4d.mp4

### CODE REVIEW

**Comment by kwea123** [comment]
Thanks for the GUI, I will check and make some updates

**Comment by kwea123** [comment]
It works correctly, but currently the rotation is a pain... This needs fix otherwise unusable

**Comment by kwea123** [comment]
Rotation is fixed. More functionalities on the way!

**Comment by collinabidi** [comment]
This crashes for me with a segmentation fault:

segfault

**Pull request merged**
